# Generated by Django 4.1 on 2024-07-24 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_alter_itemimage_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemImage',
        ),
    ]
