# Generated by Django 4.1 on 2024-07-28 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
