# Generated by Django 4.1 on 2024-08-01 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
