# Generated by Django 4.1 on 2024-08-01 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0004_userprofile_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
